{
  "id": "ch_C06FA6A23_2025-05-19_1747674386.136099_thread",
  "type": "channel",
  "channel_name": "discuss-engineering",
  "conversation_type": "thread",
  "participants": [
    "Sayan"
  ],
  "messages": [
    {
      "sender": "Sayan",
      "user_id": "U07TLK5RJBS",
      "message": "This is so weird, I added an alias in `~/.bashrc` which was recognized. This aliased command involved `git commit`  but it gave this error: `/usr/bin/env: 'python': No such file or directory`\n\nHowever, when I `source ~/.bashrc` manually I was able to run the command (and consequently git commit successfully). I wonder what the issue could be",
      "time": "10:06",
      "timestamp": "1747674386.136099",
      "is_reply": false
    },
    {
      "sender": "Sayan",
      "user_id": "U07TLK5RJBS",
      "message": "I wonder if python isn't \"set up\" when bashrc is sourced on the system being resumed but it is when I ssh into the machine",
      "time": "10:08",
      "timestamp": "1747674530.875499",
      "is_reply": true
    }
  ],
  "metadata": {
    "channel_id": "C06FA6A23",
    "channel_name": "discuss-engineering",
    "date_file": "2025-05-19.json",
    "message_count": 2,
    "start_time": "1747674386.136099",
    "end_time": "1747674530.875499",
    "is_thread": true
  }
}