{
  "id": "ch_C0516UPPMT3_2023-05-04_1683233883.803139_thread",
  "type": "channel",
  "channel_name": "aihub-feedback",
  "conversation_type": "thread",
  "participants": [
    "Hari",
    "Kathy Wu",
    "Arjun"
  ],
  "messages": [
    {
      "sender": "Kathy Wu",
      "user_id": "U03MD12PS5C",
      "message": "After uploading documents for creating my app, it gets stuck on this screen (link here (https://aihub.dev.instabase.com/apps/ai-hub/build/2e2eb858-458b-4583-a195-4e4f787b71bb)). After reloading it's still is stuck on the screen. From the network tab, it seems like run_sync is returning a `Exception Error communicating with OpenAI` error (maybe we should have the error pop up somehow?).",
      "time": "13:58",
      "timestamp": "1683233883.803139",
      "is_reply": false
    },
    {
      "sender": "Hari",
      "user_id": "UCX3XL72Q",
      "message": "@Kathy Wu This will be addressed in next bundle today/tomorrow! @Siddhant has enabled tracing and error propagation from the backend which the UI can consume. cc: @Rakesh",
      "time": "14:06",
      "timestamp": "1683234416.739429",
      "is_reply": true
    },
    {
      "sender": "Arjun",
      "user_id": "U03T41QAMN1",
      "message": "@Kathy Wu is this error for class_suggest? Did you initially see an error next to classifying and now after reloading you are seeing the purple check mark?",
      "time": "14:21",
      "timestamp": "1683235296.919029",
      "is_reply": true
    },
    {
      "sender": "Kathy Wu",
      "user_id": "U03MD12PS5C",
      "message": "no errors, it was just classifying for a few seconds and then it finished classifying but was stuck on the page",
      "time": "14:22",
      "timestamp": "1683235368.316229",
      "is_reply": true
    },
    {
      "sender": "Arjun",
      "user_id": "U03T41QAMN1",
      "message": "interesting. I think this is actually a front-end bug then. We should be showing that there was an error in classification",
      "time": "14:26",
      "timestamp": "1683235590.183379",
      "is_reply": true
    },
    {
      "sender": "Arjun",
      "user_id": "U03T41QAMN1",
      "message": "yep, I discovered the issue. Will put up a fix for this. We wonâ€™t show the exact error message but we should be showing that there was an error",
      "time": "14:29",
      "timestamp": "1683235780.440489",
      "is_reply": true
    },
    {
      "sender": "Kathy Wu",
      "user_id": "U03MD12PS5C",
      "message": "thanks!",
      "time": "14:30",
      "timestamp": "1683235808.592389",
      "is_reply": true
    }
  ],
  "metadata": {
    "channel_id": "C0516UPPMT3",
    "channel_name": "aihub-feedback",
    "date_file": "2023-05-04.json",
    "message_count": 7,
    "start_time": "1683233883.803139",
    "end_time": "1683235808.592389",
    "is_thread": true
  }
}