{
  "id": "ch_C06FA6A23_2024-03-20_1710953998.293679_thread",
  "type": "channel",
  "channel_name": "discuss-engineering",
  "conversation_type": "thread",
  "participants": [
    "Rakesh",
    "Lalit"
  ],
  "messages": [
    {
      "sender": "Lalit",
      "user_id": "U038G74CGTA",
      "message": "Hey team,\n  Getting error while build and run unit test for ibllm. Full output is attached. Can someone help solve this?\nCommand used: `make clean build run-test-local TEST_NAMES=instabase.test_tabular_data_framework`\nError:\n```HangupException\n\n  The remote server unexpectedly closed the connection.\n\n  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/dulwich/protocol.py:215 in read_pkt_line\n      211│ \n      212│         try:\n      213│             sizestr = read(4)\n      214│             if not sizestr:\n    → 215│                 raise HangupException()\n      216│             size = int(sizestr, 16)\n      217│             if size == 0:\n      218│                 if self.report_activity:\n      219│                     self.report_activity(4, \"read\")\n\nThe following error occurred when trying to handle this error:\n\n\n  HangupException\n\n  ssh: Could not resolve hostname https: nodename nor servname provided, or not known\n\n  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/dulwich/client.py:1132 in fetch_pack\n      1128│         with proto:\n      1129│             try:\n      1130│                 refs, server_capabilities = read_pkt_refs(proto.read_pkt_seq())\n      1131│             except HangupException as exc:\n    → 1132│                 raise _remote_error_from_stderr(stderr) from exc\n      1133│             (\n      1134│                 negotiated_capabilities,\n      1135│                 symrefs,\n      1136│                 agent,```",
      "time": "09:59",
      "timestamp": "1710953998.293679",
      "is_reply": false
    },
    {
      "sender": "Rakesh",
      "user_id": "U01668DGQCE",
      "message": "Lalit\nThis is more of a python package setup/download issue during poetry env setup.\nCan you try checking installing that package alone which fails to isolate problem ?",
      "time": "21:07",
      "timestamp": "1710994057.820159",
      "is_reply": true
    }
  ],
  "metadata": {
    "channel_id": "C06FA6A23",
    "channel_name": "discuss-engineering",
    "date_file": "2024-03-20.json",
    "message_count": 2,
    "start_time": "1710953998.293679",
    "end_time": "1710994057.820159",
    "is_thread": true
  }
}