{
  "id": "ch_C06FA6A23_2023-03-30_1680192871.459529_thread",
  "type": "channel",
  "channel_name": "discuss-engineering",
  "conversation_type": "thread",
  "participants": [
    "mfichman",
    "Aaron Tami"
  ],
  "messages": [
    {
      "sender": "Aaron Tami",
      "user_id": "UGG8PLD2P",
      "message": "They have these calls blocked in their QA environment, it has been blocked for over a month or two with no issues seen.  They are going to go ahead and block them in prod, I told them we don't know where this is coming from and don't anticipate any issues from blocking it since they didn't see issues in QA.\n\nWe also deploy to a number of other customers that have all outside access blocked",
      "time": "09:14",
      "timestamp": "1680192871.459529",
      "is_reply": false
    },
    {
      "sender": "mfichman",
      "user_id": "U03DZ9XUE10",
      "message": "Wow, that's crazy. Maybe we can configure Flask to not do that :slightly_smiling_face:",
      "time": "09:26",
      "timestamp": "1680193615.327009",
      "is_reply": true
    },
    {
      "sender": "Aaron Tami",
      "user_id": "UGG8PLD2P",
      "message": "im not sure that its flask... I was getting nowhere trying to research this so I actually described the issue to ChatGPT and it said that some python libraries like Flask can sometimes try to resolve dependencies at runtime lol",
      "time": "10:14",
      "timestamp": "1680196488.046329",
      "is_reply": true
    },
    {
      "sender": "mfichman",
      "user_id": "U03DZ9XUE10",
      "message": "Ahaha :slightly_smiling_face:",
      "time": "10:59",
      "timestamp": "1680199180.893359",
      "is_reply": true
    }
  ],
  "metadata": {
    "channel_id": "C06FA6A23",
    "channel_name": "discuss-engineering",
    "date_file": "2023-03-30.json",
    "message_count": 4,
    "start_time": "1680192871.459529",
    "end_time": "1680199180.893359",
    "is_thread": true
  }
}