{
  "id": "ch_C06FA6A23_2020-05-10_1589148179.178700_thread",
  "type": "channel",
  "channel_name": "discuss-engineering",
  "conversation_type": "thread",
  "participants": [
    "Eric Han",
    "Heymian"
  ],
  "messages": [
    {
      "sender": "Eric Han",
      "user_id": "UKPHNU5QE",
      "message": "Has anyone seen these errors when trying to run mypy locally with `make mypy` inside a service’s root?",
      "time": "15:02",
      "timestamp": "1589148179.178700",
      "is_reply": false
    },
    {
      "sender": "Heymian",
      "user_id": "UADQ9V8PK",
      "message": "can you try to do a `make clean mypy` ? Files may have gotten moved around and unless you clean, you’ll end up with the same file in two places.",
      "time": "16:53",
      "timestamp": "1589154820.179100",
      "is_reply": true
    }
  ],
  "metadata": {
    "channel_id": "C06FA6A23",
    "channel_name": "discuss-engineering",
    "date_file": "2020-05-10.json",
    "message_count": 2,
    "start_time": "1589148179.178700",
    "end_time": "1589154820.179100",
    "is_thread": true
  }
}