{
  "id": "dm_D03LK3XUJUA_2024-11-01_1730490925.468099",
  "type": "dm",
  "participants": [
    "Anil",
    "Abhishek Adupa"
  ],
  "messages": [
    {
      "sender": "Anil",
      "user_id": "U01BH8XBR55",
      "message": "one more bug",
      "time": "12:55",
      "timestamp": "1730490925.468099",
      "is_reply": false
    },
    {
      "sender": "Anil",
      "user_id": "U01BH8XBR55",
      "message": "are you free for a quick huddle?",
      "time": "12:55",
      "timestamp": "1730490945.050329",
      "is_reply": false
    },
    {
      "sender": "Abhishek Adupa",
      "user_id": "U03JYD51DM2",
      "message": "Hi, Yes Anil, 2 mins.",
      "time": "12:57",
      "timestamp": "1730491068.946329",
      "is_reply": false
    },
    {
      "sender": "Anil",
      "user_id": "U01BH8XBR55",
      "message": ":thank_you:",
      "time": "12:57",
      "timestamp": "1730491074.659409",
      "is_reply": false
    },
    {
      "sender": "Anil",
      "user_id": "U01BH8XBR55",
      "message": "```       smessage: Received non-retryable error from api-server celery handler [TaskID=2a546f61-3ad9-4ad7-a2f7-95fca4486900-Stage6, error=code = INTERNAL msg = failed to run task 2a546f61-3ad9-4ad7-a2f7-95fca4486900-Stage6. Error: Post \"http://localhost:25555/api/v1/celery-handler/run/2a546f61-3ad9-4ad7-a2f7-95fca4486900-Stage6\": dial tcp [::1]:25555: connect: connection refused]```",
      "time": "13:04",
      "timestamp": "1730491454.800049",
      "is_reply": false
    },
    {
      "sender": "Abhishek Adupa",
      "user_id": "U03JYD51DM2",
      "message": "retry for internal/default, but have a limit on number of retries before failing is also a good option",
      "time": "13:20",
      "timestamp": "1730492448.743219",
      "is_reply": false
    },
    {
      "sender": "Abhishek Adupa",
      "user_id": "U03JYD51DM2",
      "message": "like we do on the app-tasks side.",
      "time": "13:21",
      "timestamp": "1730492484.766419",
      "is_reply": false
    },
    {
      "sender": "Anil",
      "user_id": "U01BH8XBR55",
      "message": "in past 24 hour 3 jobs failed due to this. total of 80 tasks failed due to this",
      "time": "13:23",
      "timestamp": "1730492638.745169",
      "is_reply": false
    },
    {
      "sender": "Anil",
      "user_id": "U01BH8XBR55",
      "message": "intermediate tasks failing didnâ€™t affect job completing as some other tasks might have succeeded",
      "time": "13:24",
      "timestamp": "1730492654.542069",
      "is_reply": false
    },
    {
      "sender": "Anil",
      "user_id": "U01BH8XBR55",
      "message": "only when last task the write summary results failing leads to job failure",
      "time": "13:24",
      "timestamp": "1730492672.955359",
      "is_reply": false
    }
  ],
  "metadata": {
    "dm_id": "D03LK3XUJUA",
    "date_file": "2024-11-01.json",
    "message_count": 10,
    "start_time": "1730490925.468099",
    "end_time": "1730492672.955359"
  }
}